### ISSUE TITLE
did not pass OVF specification conformance [ESXI 6.7]

### ISSUE THREAD

**Issue by karemfaisal** [alph4w0lf/LokiX#1]
Opening the OVA with VM workstation 15.5.6 gives an error 
```did not pass OVF specification conformance or virtual hardware compliance checks```
![Vmworkstation](https://user-images.githubusercontent.com/11690936/97860736-556d3c00-1d0b-11eb-9eb6-16529e294e4a.PNG)

but clicking retry, it solves the problem, **Although doing that on ESXi 6.7, it failed to run**

![ESXI](https://user-images.githubusercontent.com/11690936/97860893-949b8d00-1d0b-11eb-930a-208569d70403.PNG)

**Comment by alph4w0lf** [comment]
Welcome Karem,

It seems that the hardware version set in the OVA is not accepted by your ESXi version. For that, you can either create a new VM and import the hardisk directly from the OVA file (you can rename it to .zip and unzip it to get the disk file).
Explained in details here:
https://www.vionblog.com/migrate-virtualbox-vmware-esxi-6-5/

Another solution to the issue can be achieved using "VMware OVF Tools" following the guide in here:
https://felixcentmerino.wordpress.com/virtualization/migrate-virtual-machine-from-oracle-virtualbox-to-esxi-5-5/

I will be uploading another "OVA" file soon specifically for VMware.

Thank you for reporting this.
