### ISSUE TITLE
Can not configure a static ip

### ISSUE THREAD

**Issue by Morjanoo10** [alph4w0lf/LokiX#2]
**Hello friend..
     I've been stuck at "Configure Static IP address on Server" steps where in step NO.1: Locate and edit with administrative privileges the /etc/netplan/50-cloud-init.yaml file.
I've tried to locate the file by "ls" command but still not there can you provide me a hint?**
![2021-01-13_131218](https://user-images.githubusercontent.com/47706671/104438638-41627800-55a1-11eb-83df-9adc353f0558.jpg)

**Comment by alph4w0lf** [comment]
Hi there,

You found the right file but you are using "cd" to access the file, you should use "nano" instead to view and modify the file contents.

Good luck,
